# Site settings
title: Charlotte-NGS
email: ngs.charlotte@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Charlotte-ngs was meant to be a project platform for all kinds
  of small projects in bioinformatics and computational biology.
  So far its is mainly a blog on programming in R and on teaching.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://charlotte-ngs.github.io" # the base hostname & protocol for your site
twitter_username: charlotte_ngs
github_username:  charlotte-ngs
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
